"""initial schema

Revision ID: 9873bb945da0
Revises: 
Create Date: 2026-10-04 03:39:16.459240
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '9873bb945da0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=96), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('grounding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_entity', 'ai_interactions', ['entity_type', 'entity_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_table('holidays',
    sa.Column('calendar_code', sa.String(length=16), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('half_day', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('calendar_code', 'day')
    )
    op.create_table('institutions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('ix_jobs_ready', 'jobs', ['status', 'run_at'], unique=False)
    op.create_table('sim_planned_loads',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('institution_code', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_planned_loads_due_at'), 'sim_planned_loads', ['due_at'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('contract_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spec_hash', sa.String(length=64), nullable=False),
    sa.Column('origin', sa.String(length=24), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('backtest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'version')
    )
    op.create_index(op.f('ix_contract_versions_institution_id'), 'contract_versions', ['institution_id'], unique=False)
    op.create_table('sim_truths',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('slot_key', sa.String(length=48), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppressions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occurrences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('slot_key', sa.String(length=48), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('expected', sa.Boolean(), nullable=False),
    sa.Column('window_start_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('load_count', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('baselines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_severity', sa.String(length=16), nullable=True),
    sa.Column('contract_version_id', sa.Uuid(), nullable=True),
    sa.Column('spec_hash', sa.String(length=64), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluded_from_baseline', sa.Boolean(), nullable=False),
    sa.Column('regime_break', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'slot_key', 'business_date')
    )
    op.create_index('ix_occ_date', 'occurrences', ['business_date'], unique=False)
    op.create_index('ix_occ_status_deadline', 'occurrences', ['status', 'deadline_utc'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurrence_id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('contract_version_id', sa.Uuid(), nullable=True),
    sa.Column('spec_hash', sa.String(length=64), nullable=True),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_occurrence_id'), 'evaluations', ['occurrence_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.BigInteger(), sa.Identity(always=False, start=1001), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('occurrence_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('fingerprint', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.Column('impact_customers', sa.Float(), nullable=True),
    sa.Column('impact_amount', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.Column('assignee', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('resolution', sa.String(length=24), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('suppressed_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrences.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['suppressed_by'], ['suppressions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('ix_incident_status_priority', 'incidents', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_incidents_institution_id'), 'incidents', ['institution_id'], unique=False)
    op.create_index(op.f('ix_incidents_occurrence_id'), 'incidents', ['occurrence_id'], unique=False)
    op.create_index('uq_incident_open_fingerprint', 'incidents', ['fingerprint'], unique=True, postgresql_where=sa.text("status <> 'RESOLVED'"))
    op.create_table('loads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('slot_hint', sa.String(length=48), nullable=True),
    sa.Column('record_count', sa.BigInteger(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('customer_count', sa.BigInteger(), nullable=False),
    sa.Column('zero_amount_count', sa.BigInteger(), nullable=False),
    sa.Column('negative_amount_count', sa.BigInteger(), nullable=False),
    sa.Column('duplicate_record_count', sa.BigInteger(), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('occurrence_id', sa.Uuid(), nullable=True),
    sa.Column('assignment_reason', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'external_id')
    )
    op.create_index('ix_loads_inst_hash', 'loads', ['institution_id', 'content_hash'], unique=False)
    op.create_index('ix_loads_inst_received', 'loads', ['institution_id', 'received_at'], unique=False)
    op.create_index(op.f('ix_loads_occurrence_id'), 'loads', ['occurrence_id'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_incident_id'), 'notifications', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_incident_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_loads_occurrence_id'), table_name='loads')
    op.drop_index('ix_loads_inst_received', table_name='loads')
    op.drop_index('ix_loads_inst_hash', table_name='loads')
    op.drop_table('loads')
    op.drop_index('uq_incident_open_fingerprint', table_name='incidents', postgresql_where=sa.text("status <> 'RESOLVED'"))
    op.drop_index(op.f('ix_incidents_occurrence_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_institution_id'), table_name='incidents')
    op.drop_index('ix_incident_status_priority', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_evaluations_occurrence_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('ix_occ_status_deadline', table_name='occurrences')
    op.drop_index('ix_occ_date', table_name='occurrences')
    op.drop_table('occurrences')
    op.drop_table('suppressions')
    op.drop_table('sim_truths')
    op.drop_index(op.f('ix_contract_versions_institution_id'), table_name='contract_versions')
    op.drop_table('contract_versions')
    op.drop_table('users')
    op.drop_index(op.f('ix_sim_planned_loads_due_at'), table_name='sim_planned_loads')
    op.drop_table('sim_planned_loads')
    op.drop_index('ix_jobs_ready', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('institutions')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_ai_entity', table_name='ai_interactions')
    op.drop_table('ai_interactions')
    # ### end Alembic commands ###
